package app

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

// Regex patterns for detecting split volumes
var (
	// Standard split format: archive.ext.001, archive.ext.002, etc.
	// Supports: 7z, zip, tar, gz, xz, bz2, rar
	splitStandardRe = regexp.MustCompile(`(?i)\.(7z|zip|tar|gz|xz|bz2|rar)\.[0-9]{3,}$`)

	// RAR part format: archive.part001.rar, archive.part002.rar, etc.
	splitRarPartRe = regexp.MustCompile(`(?i)\.part[0-9]{3,}\.rar$`)

	// RAR old format: archive.rar, archive.r00, archive.r01, etc.
	splitRarOldRe = regexp.MustCompile(`(?i)\.r[0-9]{2,}$`)
)

// ArchiveType represents the type of archive detected
type ArchiveType int

const (
	ArchiveStandard ArchiveType = iota
	ArchiveSplitStandard
	ArchiveSplitRarPart
	ArchiveSplitRarOld
)

// ArchiveInfo contains metadata about an archive file
type ArchiveInfo struct {
	OriginalName   string
	NormalizedName string
	Type           ArchiveType
	IsSplit        bool
}

// AnalyzeArchive analyzes an archive path and returns metadata
func AnalyzeArchive(path string) ArchiveInfo {
	base := filepath.Base(path)
	normalized := normalizeArchiveName(path)

	info := ArchiveInfo{
		OriginalName:   base,
		NormalizedName: normalized,
		Type:           ArchiveStandard,
		IsSplit:        normalized != base,
	}

	switch {
	case splitStandardRe.MatchString(base):
		info.Type = ArchiveSplitStandard
	case splitRarPartRe.MatchString(base):
		info.Type = ArchiveSplitRarPart
	case splitRarOldRe.MatchString(base):
		info.Type = ArchiveSplitRarOld
	}

	return info
}

// normalizeArchiveName extracts the logical archive name from a file path.
// It handles standard archives and various split volume formats:
//   - Standard split: archive.7z.001 -> archive.7z
//   - RAR part: archive.part001.rar -> archive.rar
//   - RAR old: archive.r00 -> archive.rar
func normalizeArchiveName(path string) string {
	// Normalize path separators for cross-platform base name extraction
	base := filepath.Base(strings.ReplaceAll(path, "\\", "/"))

	// Standard split format: *.ext.NNN
	if splitStandardRe.MatchString(base) {
		ext := filepath.Ext(base) // .001
		return strings.TrimSuffix(base, ext)
	}

	// RAR part format: *.partNNN.rar -> *.rar (preserve original case)
	if splitRarPartRe.MatchString(base) {
		loc := splitRarPartRe.FindStringIndex(base)
		if loc != nil {
			matched := base[loc[0]:loc[1]]
			rarExt := matched[len(matched)-4:] // ".rar", ".RAR", ".Rar", etc.
			return base[:loc[0]] + rarExt
		}
	}

	// RAR old format: *.rNN -> *.rar (preserve case from original extension)
	if splitRarOldRe.MatchString(base) {
		ext := filepath.Ext(base) // .r00 or .R00
		prefix := strings.TrimSuffix(base, ext)
		if ext[1] >= 'A' && ext[1] <= 'Z' {
			return prefix + ".RAR"
		}
		return prefix + ".rar"
	}

	return base
}

// joinEntry joins a prefix path with an entry name, handling slash separators.
// It ensures consistent forward-slash separators regardless of OS.
func joinEntry(prefix, name string) string {
	if prefix == "" {
		return name
	}
	return strings.ReplaceAll(filepath.Join(prefix, name), "\\", "/")
}

// GetPasswordForArchive attempts to find the password for an archive using a smart lookup strategy:
//  1. Exact absolute path match (fastest, zero ambiguity)
//  2. Global fallback search (handles moved archives)
//  3. Ambiguity resolution (throws error if multiple matches)
//
// Returns the password, the matching KeePass entry path, or an error.
func GetPasswordForArchive(kp PasswordProvider, entryPathPrefix, archivePath string) ([]byte, string, error) {
	if kp == nil {
		return nil, "", fmt.Errorf("password provider is nil")
	}

	if archivePath == "" {
		return nil, "", fmt.Errorf("archive path is empty")
	}

	info := AnalyzeArchive(archivePath)
	tried := make([]string, 0, 3)

	// The KeePass title is now just the base filename of the archive.
	exactGroup := entryPathPrefix
	if exactGroup == "" {
		exactGroup = "Archives/AutoGenerated"
	}

	exactPath := exactGroup
	if !strings.HasSuffix(exactPath, "/") {
		exactPath += "/"
	}
	exactPath += filepath.Base(archivePath)

	// 1. Try exact match first
	tried = append(tried, exactPath)
	if pass, err := kp.GetPassword(exactPath); err == nil {
		return pass, exactPath, nil
	}

	// Split archives might be saved under the normalized name (e.g. archive.7z instead of archive.7z.001)
	if info.IsSplit {
		exactPathNormalized := exactGroup
		if !strings.HasSuffix(exactPathNormalized, "/") {
			exactPathNormalized += "/"
		}
		exactPathNormalized += info.NormalizedName

		tried = append(tried, exactPathNormalized)
		if pass, err := kp.GetPassword(exactPathNormalized); err == nil {
			return pass, exactPathNormalized, nil
		}
	}

	// 2. Exact match failed, do global fallback search for the base name
	searchTarget := info.OriginalName
	if info.IsSplit {
		// Prefer searching for the base normalized name, it's safer
		searchTarget = info.NormalizedName
	}

	results, err := kp.Search(searchTarget)
	if err == nil && len(results) > 0 {
		var matchingPaths []string
		for _, res := range results {
			// Ensure it belongs to our configured prefix group (ignore unrelated KeePass entries)
			if strings.HasPrefix(filepath.ToSlash(res), filepath.ToSlash(entryPathPrefix)) {
				matchingPaths = append(matchingPaths, res)
			}
		}

		// 3. Ambiguity resolution
		if len(matchingPaths) == 1 {
			// Found exactly one! A moved or renamed archive match.
			pass, err := kp.GetPassword(matchingPaths[0])
			if err == nil {
				return pass, matchingPaths[0], nil
			}
			return nil, "", err
		} else if len(matchingPaths) > 1 {
			return nil, "", fmt.Errorf("multiple passwords found for '%s' in KeePass. Please rename the archive back or use '7zkpxc rename' to resolve the collision", searchTarget)
		}
	}

	return nil, "", &PasswordNotFoundError{
		ArchiveName: info.OriginalName,
		Tried:       tried,
	}
}

// PasswordProvider is an interface for password retrieval
type PasswordProvider interface {
	GetPassword(key string) ([]byte, error)
	Search(query string) ([]string, error)
}

// PasswordNotFoundError is returned when no password can be found for an archive
type PasswordNotFoundError struct {
	ArchiveName string
	Tried       []string
}

func (e *PasswordNotFoundError) Error() string {
	return fmt.Sprintf("password not found for archive '%s' (tried: %s)",
		e.ArchiveName, strings.Join(e.Tried, ", "))
}

// IsPasswordNotFound checks if an error is a PasswordNotFoundError
func IsPasswordNotFound(err error) bool {
	_, ok := err.(*PasswordNotFoundError)
	return ok
}
