package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/viper"
)

const (
	PasswordLengthMin     = 32
	PasswordLengthMax     = 128
	PasswordLengthDefault = 64
)

// Config holds the application configuration
type Config struct {
	General  GeneralConfig  `mapstructure:"general"`
	SevenZip SevenZipConfig `mapstructure:"sevenzip"`
}

type GeneralConfig struct {
	KdbxPath       string `mapstructure:"kdbx_path"`
	DefaultGroup   string `mapstructure:"default_group"`
	UseKeyring     bool   `mapstructure:"use_keyring"`
	PasswordLength int    `mapstructure:"password_length"`
}

type SevenZipConfig struct {
	DefaultArgs []string `mapstructure:"default_args"`
	BinaryPath  string   `mapstructure:"binary_path"`
}

// LoadConfig reads configuration from file and environment variables
func LoadConfig() (*Config, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get user home directory: %w", err)
	}

	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath(filepath.Join(home, ".config", "7zkpxc"))
	viper.AddConfigPath(".")

	// Set Defaults
	viper.SetDefault("general.default_group", "Archives/AutoGenerated")
	viper.SetDefault("general.use_keyring", true)
	viper.SetDefault("general.password_length", PasswordLengthDefault)
	viper.SetDefault("sevenzip.default_args", []string{"-mhe=on", "-mx=9"})
	viper.SetDefault("sevenzip.binary_path", "7z")

	// Environment variables
	viper.SetEnvPrefix("SZKPXC")
	viper.AutomaticEnv()

	// Read Config
	if err := viper.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			return nil, fmt.Errorf("error reading config file: %w", err)
		}
		// Config file not found is okay, we use defaults
	}

	var cfg Config
	if err := viper.Unmarshal(&cfg); err != nil {
		return nil, fmt.Errorf("config parse error: %w", err)
	}

	// Handle default
	if cfg.General.PasswordLength == 0 {
		cfg.General.PasswordLength = PasswordLengthDefault
	}

	// Validate range
	if cfg.General.PasswordLength < PasswordLengthMin || cfg.General.PasswordLength > PasswordLengthMax {
		return nil, fmt.Errorf("invalid password_length: %d (must be between %d and %d)",
			cfg.General.PasswordLength, PasswordLengthMin, PasswordLengthMax)
	}

	return &cfg, nil
}

// SaveConfig writes the configuration to the default config file
func SaveConfig(cfg *Config) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	configDir := filepath.Join(home, ".config", "7zkpxc")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return err
	}

	viper.Set("general.kdbx_path", cfg.General.KdbxPath)
	viper.Set("general.default_group", cfg.General.DefaultGroup)
	viper.Set("general.use_keyring", cfg.General.UseKeyring)
	viper.Set("general.password_length", cfg.General.PasswordLength)
	viper.Set("sevenzip.default_args", cfg.SevenZip.DefaultArgs)
	viper.Set("sevenzip.binary_path", cfg.SevenZip.BinaryPath)

	configPath := filepath.Join(configDir, "config.yaml")
	return viper.WriteConfigAs(configPath)
}
