package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/viper"
)

const (
	PasswordLengthMin     = 32
	PasswordLengthMax     = 128
	PasswordLengthDefault = 64
)

// Config holds the application configuration
type Config struct {
	General  GeneralConfig  `mapstructure:"general" yaml:"general"`
	SevenZip SevenZipConfig `mapstructure:"sevenzip" yaml:"sevenzip"`
}

type GeneralConfig struct {
	KdbxPath       string `mapstructure:"kdbx_path" yaml:"kdbx_path"`
	DefaultGroup   string `mapstructure:"default_group" yaml:"default_group"`
	// UseKeyring is persisted in the config file but not yet acted on.
	// TODO: implement OS keyring integration (e.g. via keyring package).
	UseKeyring     bool   `mapstructure:"use_keyring" yaml:"use_keyring"`
	PasswordLength int    `mapstructure:"password_length" yaml:"password_length"`
}

type SevenZipConfig struct {
	DefaultArgs []string `mapstructure:"default_args" yaml:"default_args"`
	BinaryPath  string   `mapstructure:"binary_path" yaml:"binary_path"`
}

var (
	// cachedConfig stores the loaded config to prevent redundant disk reads.
	// In a short-lived CLI this saves ~1ms per call, but avoids parsing twice
	// (once in checkDependencies and once in the command body).
	cachedConfig *Config
)

// ClearCache forces the next LoadConfig call to read from disk/env again.
// Useful for tests.
func ClearCache() {
	cachedConfig = nil
}

// LoadConfig reads configuration from file and environment variables.
// It returns a cached copy if already loaded during this execution.
func LoadConfig() (*Config, error) {
	if cachedConfig != nil {
		return cachedConfig, nil
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get user home directory: %w", err)
	}

	v := viper.New()
	v.SetConfigName("config")
	v.SetConfigType("yaml")
	v.AddConfigPath(filepath.Join(home, ".config", "7zkpxc"))
	v.AddConfigPath(".")

	// Defaults
	v.SetDefault("general.default_group", "Archives/AutoGenerated")
	v.SetDefault("general.use_keyring", true)
	v.SetDefault("general.password_length", PasswordLengthDefault)
	v.SetDefault("sevenzip.default_args", []string{"-mhe=on", "-mx=9"})
	v.SetDefault("sevenzip.binary_path", "7z")

	// Environment variables (prefix: 7ZKPXC_)
	v.SetEnvPrefix("7ZKPXC")
	v.AutomaticEnv()

	if err := v.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			return nil, fmt.Errorf("error reading config file: %w", err)
		}
	}

	var cfg Config
	if err := v.Unmarshal(&cfg); err != nil {
		return nil, fmt.Errorf("config parse error: %w", err)
	}

	// kdbx_path has no valid default — only set by `7zkpxc init`
	if cfg.General.KdbxPath == "" {
		return nil, fmt.Errorf("KeePassXC database path is not configured\n\nRun '7zkpxc init' first to set up your configuration")
	}

	if cfg.General.PasswordLength == 0 {
		cfg.General.PasswordLength = PasswordLengthDefault
	}

	if cfg.General.PasswordLength < PasswordLengthMin || cfg.General.PasswordLength > PasswordLengthMax {
		return nil, fmt.Errorf("invalid password_length: %d (must be between %d and %d)",
			cfg.General.PasswordLength, PasswordLengthMin, PasswordLengthMax)
	}

	cachedConfig = &cfg
	return &cfg, nil
}

// SaveConfig writes the configuration to the default config file using Viper.
// Note: the interactive `init` command uses saveConfigWithComments instead,
// which produces a commented YAML that survives manual edits more gracefully.
// This function is available for programmatic writes that do not need comments.
func SaveConfig(cfg *Config) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	configDir := filepath.Join(home, ".config", "7zkpxc")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return err
	}

	v := viper.New()
	v.Set("general.kdbx_path", cfg.General.KdbxPath)
	v.Set("general.default_group", cfg.General.DefaultGroup)
	v.Set("general.use_keyring", cfg.General.UseKeyring)
	v.Set("general.password_length", cfg.General.PasswordLength)
	v.Set("sevenzip.default_args", cfg.SevenZip.DefaultArgs)
	v.Set("sevenzip.binary_path", cfg.SevenZip.BinaryPath)

	configPath := filepath.Join(configDir, "config.yaml")
	return v.WriteConfigAs(configPath)
}
